terms:
- airbus
- ms-21
- авиакомпан
- аэродром
- аэропорт
- аэрофлот
- боинг
- взлетн полос
- внуково
- воздушн гаван
- домодедово
- дьюти фри
- задержк рейс
- лоукостер
- отмен рейс
- паспортн контрол
- перрон
- пулково
- ручн кладь
- суперджет
- таможн
- телетрап
- трап
- чартер
- шереметьево
