terms:
- дтп
- инсульт
- инфаркт
- искусственн дыхан
- катастроф
- катафалк
- кладбищ
- крушение
- лобов столкновен
- могил
- некролог
- онколог
- онкоцентр
- отпеван
- паллиативн
- панихид
- перевернулс
- поминовен
- похорон
- пьян водитель
- реанимац
- сбит пешеход
- скоропомощн
- травмпункт
- траур
- урна с прахом
- хоспис
