terms:
- взрыв бытов
- возгоран
- вытаскивал из-под завал
- задымлен
- коммунальн авари
- обрушен
- огнетушит
- пожар
- пожарн
- пожары
- потоп
- промальп
- прорыв труб
- спасател
- спасен
- утечк газ
- эвакуац
