terms:
- mtv
- айдо
- альбом
- баритон
- бас-гитар
- вокалист
- гастрол
- грамми
- диджей
- евровиден
- к-поп
- клип
- концерт
- лейбл
- муз-тв
- песня года
- поп-звезд
- продюсер
- рок-групп
- рэп-исполнит
- саундтрек
- сингл
- солист
- сопрано
- спотифай
- стриминг
- турне
- ударник
- фан-клуб
- фандом
- хип-хоп
- хит-парад
- чарт
- шансон
- эстрад
