terms:
- буи цунами
- весенн паводок
- вулкан
- вулканическ бомб
- вулканическ газ
- вулканическ конус
- вулканическ купол
- вулканическ пепел
- вулканическ пояс
- вулканолог
- гидрометцентр
- дым от лесн пожар
- жертвы стихийн бедстви
- зажорн наводнен
- затоплен дом
- заторн наводнен
- землетрясен
- зона затоплен
- зона подтоплен
- зона цунами
- извержен вулкан
- кратер вулкан
- лавина сошла
- лавиноопасн склон
- лесн пожар
- магнитуд
- магнитуд по шкале
- наводнен
- нагонн наводнен
- огнен смерч
- оползнеопасн участок
- осенн паводок
- отлив перед цунами
- очаг землетрясен
- очаг цунами
- паводок
- подтоплен
- подтопил
- прорыв дамб
- прорыв плотин
- росгидромет
- сезон ураганов
- сейсмическ
- сейсмическ волн в океан
- сейсмическ пояс
- сейсмичн
- сейсмоактивн
- сейсмограф
- сейсмозон
- сейсмолог
- сейсмологическ служб
- сейсмоопасн
- сейсмоопасн зон
- сейсмостанц
- сейсмостойк
- селев поток
- сель сошел
- система предупрежд цунами
- снежн лавин
- стихийн бедстви
- стратовулкан
- супервулкан
- сход селев потока
- тайфунн сезон
- торнадо
- торфян пожар
- траектория ураган
- ураган категорий
- цунами
- цунами-опасн
- чрезвычайн ситуаци природн
- штормов нагон
- штормов предупрежд
- штормовой предупрежд
- щитовой вулкан
- эвакуац населен
- эпицентр землетряс
- эпицентр на глубин
