terms:
- аллах
- архимандрит
- библи
- благодатн огонь
- буддизм
- ваххабизм
- вечерня
- всевышн
- всенощн
- диакон
- евангели
- епархия
- епископ
- икон
- ислам
- исповедь
- иудаизм
- ифтар
- католик
- коран
- крестн ход
- крещен
- курбан-байрам
- лавра
- литурги
- мечеть
- миропомаз
- митрополит
- молебен
- монастырь
- мощи
- мулла
- мусульман
- настоятель
- патриарх
- православ
- причастие
- протестант
- протоиерей
- раввин
- рамадан
- рпц
- сайентолог
- священник
- синагог
- синод
- скит
- соборован
- старец
- тора
- ураза-байрам
- утреня
- храм
- церков
- часовня
- чудотворн
- юродив
