terms:
- bmx
- cs:go
- dota
- fifa
- isu
- khl
- mma
- nba
- nhl
- rusada
- uefa
- ufc
- wada
- айкидо
- академическ гребл
- альпинизм
- артистическ плаван
- бадминтон
- байдарк
- баскетбол
- баттерфляй
- бейсбол
- биатлон
- бобсле
- бокс
- бразильск джиу
- брасс
- брейк-данс
- брейкинг
- вада
- велоспорт
- водн поло
- водного поло
- водное поло
- водному поло
- водном поло
- водным поло
- волейбол
- вольн борьб
- вольной борьб
- вольная борьб
- вольную борьб
- вратарь
- выездк
- гандбол
- гимнаст
- горн лыж
- гран-при
- гребл
- греко римск
- греко-римск
- грепплинг
- гто
- джиу-джитсу
- дзюдо
- динамо
- дисквалификац
- допинг
- заплыв
- защитник
- зенит
- каноэ
- карате
- керлинг
- киберспорт
- кикбокс
- клюшк
- конкур
- конн спорт
- конькобеж
- крикет
- крол
- кубок гагарина
- кубок стэнли
- кхл
- легк атлет
- либеро
- лига европы
- лига чемпионов
- локомотив
- лучник
- лучниц
- лыжн
- лыжн двоеборь
- марафон
- метани диска
- метани копья
- метани молота
- мотоспорт
- муай-тай
- нападающ
- настолб теннис
- нба
- нхл
- олимп
- панкратион
- паралимп
- парусн спорт
- первая лига
- пятиборь
- пинг-понг
- плаван
- пляжн волейбол
- пловц
- плей-оф
- плей-офф
- полузащитник
- прыжк в воду
- прыжк в высот
- прыжк в длин
- прыжк с шест
- прыжк тройн
- ралли
- регби
- роднин
- рукопашн бой
- рпл
- самбо
- санн спорт
- саночник
- серфинг
- сеттер
- синхронист
- синхронн плаван
- скейтборд
- скелетон
- скалолазан
- смешанн единоборств
- сноуборд
- современн пятиборь
- софтбол
- спартак
- спартакиада
- спортивн ходьб
- спринт
- стартов тумб
- сумо
- суперкубок
- тайск бокс
- теннис
- толкани ядра
- трамплин
- трансфер
- триатлон
- троеборь
- турнир
- тхэквондо
- тхэквондист
- тяжел атлет
- уефа
- ультрас
- универсиада
- ушу
- фехтован
- фигурист
- фигурн
- финал четырех
- фифа
- фристайл
- футбол
- хоккей
- хоккеист
- хореограф
- художественн гимнаст
- цска
- чемпионат
- шайб
- шахмат
- шорт-трек
- эстафет
- юфс
