terms:
- cs:go
- dota
- fifa
- isu
- khl
- mma
- nba
- nhl
- rusada
- uefa
- wada
- альпинизм
- бадминтон
- байдарк
- баскетбол
- баттерфляй
- биатлон
- бокс
- брасс
- вада
- велоспорт
- волейбол
- вольн борьб
- вратарь
- гандбол
- гимнаст
- гран-при
- греко-римск
- гто
- дзюдо
- динамо
- дисквалификац
- допинг
- заплыв
- защитник
- зенит
- каноэ
- карате
- керлинг
- киберспорт
- клюшк
- конькобеж
- крол
- кубок гагарина
- кубок стэнли
- кхл
- легк атлет
- либеро
- лига европы
- лига чемпионов
- локомотив
- лыжн
- марафон
- мотоспорт
- нападающ
- нба
- нхл
- олимп
- паралимп
- первая лига
- плей-оф
- плей-офф
- полузащитник
- ралли
- регби
- роднин
- рпл
- самбо
- серфинг
- сеттер
- скейтборд
- смешанн единоборств
- сноуборд
- спартак
- спартакиада
- спринт
- стартов тумб
- суперкубок
- теннис
- трамплин
- трансфер
- триатлон
- турнир
- тхэквондо
- тяжел атлет
- уефа
- ультрас
- универсиада
- фехтован
- фигурист
- фигурн
- финал четырех
- фифа
- футбол
- хоккей
- хореограф
- цска
- чемпионат
- шайб
- шахмат
- шорт-трек
- эстафет
